# Generated by Django 5.1.1 on 2024-09-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_description_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(max_length=120),
        ),
    ]
