# Generated by Django 2.1.7 on 2025-01-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
