# Generated by Django 2.1.7 on 2024-09-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240907_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newfield',
            field=models.TextField(blank=True, null=True),
        ),
    ]
