# Generated by Django 5.1 on 2024-08-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("trend", models.DecimalField(decimal_places=2, max_digits=4)),
                ("status", models.BooleanField()),
            ],
        ),
    ]
