# Generated by Django 5.1 on 2024-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.TextField(default="NA"),
        ),
    ]
