# Generated by Django 5.1 on 2024-08-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_poll_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="status",
        ),
        migrations.AddField(
            model_name="poll",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
