# Generated by Django 5.1 on 2024-08-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_poll_status_poll_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.TextField(),
        ),
    ]
