# Generated by Django 5.1.2 on 2024-10-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(default="This is an item"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="About this item"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.TextField(default="Price"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(default="Item"),
        ),
    ]
