# Generated by Django 5.1.2 on 2024-10-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_summary_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Item", max_length=100),
        ),
    ]
