# Generated by Django 4.2.13 on 2024-06-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default="this is cool!"),
        ),
    ]
