# Generated by Django 5.1.2 on 2024-10-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
