# Generated by Django 4.0 on 2024-06-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proddoct',
            name='price',
        ),
    ]
